name: Build with Nuitka

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Compile with Nuitka
        run: |
          nuitka ^
            --standalone ^
            --enable-plugin=pyside6 ^
            --include-data-file=resources\icons\aikeyboard.ico=aikeyboard.ico ^
            --windows-icon-from-ico=resources\icons\aikeyboard.ico ^
            --output-dir=dist ^
            src\aikeyboard\AIKeyboard.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIKeyboard-Windows
          path: dist\AIKeyboard.dist\

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libxcb-xinerama0
          pip install -r requirements.txt
          pip install nuitka

      - name: Compile with Nuitka
        run: |
          nuitka \
            --standalone \
            --enable-plugin=pyside6 \
            --include-data-file=resources/icons/aikeyboard.ico=aikeyboard.ico \
            --output-dir=dist \
            src/aikeyboard/AIKeyboard.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIKeyboard-Linux
          path: dist/AIKeyboard.dist/
